# File: .gitlab-ci.yml
#
workflow:
  rules:
    # run on main always:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # never run anywhere else:
    - when: never

stages:
  - deploy_mod3_webapp

deploy:
  stage: deploy_mod3_webapp
  image: google/cloud-sdk
  script:
    - echo $MOD3_SERVICEACCOUNT_KEY > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit --config=cloudbuild.yaml --gcs-log-dir=gs://mod3_webapp_build_logs
