---
# File: cloudbuild.yaml
substitutions:
  WEBAPP_VERSION: '0.0.2'
steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/bone-idol/university/webapp:${WEBAPP_VERSION}'
      - '.'
  # push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/bone-idol/university/webapp:${WEBAPP_VERSION}'
  # deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'webapp'
      - '--image'
      - 'europe-west1-docker.pkg.dev/bone-idol/university/webapp:${WEBAPP_VERSION}'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '0.5'
      - '--concurrency'
      - '2'
      - '--max-instances'
      - '2'
      - '--min-instances'
      - '0'
  # set custom domain
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    args:
      - 'gcloud'
      - 'beta'
      - 'run'
      - 'domain-mappings'
      - 'create'
      - '--service'
      - 'webapp'
      - '--domain'
      - 'mod3.bone-idol.net'
      - '--region'
      - 'europe-west1'
